# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param power.BramSDPPropagationFix 1
set_param chipscope.maxJobs 3
set_param power.enableUnconnectedCarry8PinPower 1
set_param power.enableCarry8RouteBelPower 1
set_param power.enableLutRouteBelPower 1
create_project -in_memory -part xcvu13p-fhgb2104-2-i

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Xilinx/Verilog/MMU_240607/MMU_240607.cache/wt [current_project]
set_property parent.project_path D:/Xilinx/Verilog/MMU_240607/MMU_240607.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/Xilinx/Verilog/MMU_240607/MMU_240607.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  D:/Xilinx/Verilog/MMU_240607/MMU_240607.srcs/sources_1/new/cFifo1.v
  D:/Xilinx/Verilog/MMU_240607/MMU_240607.srcs/sources_1/new/contTap.v
  D:/Xilinx/Verilog/MMU_240607/MMU_240607.srcs/sources_1/new/delay1U.v
  D:/Xilinx/Verilog/MMU_240607/MMU_240607.srcs/sources_1/new/delay1Unit.v
  D:/Xilinx/Verilog/MMU_240607/MMU_240607.srcs/sources_1/new/delay2Unit.v
  D:/Xilinx/Verilog/MMU_240607/MMU_240607.srcs/sources_1/new/receiver.v
  D:/Xilinx/Verilog/MMU_240607/MMU_240607.srcs/sources_1/new/relay.v
  D:/Xilinx/Verilog/MMU_240607/MMU_240607.srcs/sources_1/new/sender.v
  D:/Xilinx/Verilog/MMU_240607/MMU_240607.srcs/sources_1/new/cMutexMerge3_1b.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top cMutexMerge3_1b -part xcvu13p-fhgb2104-2-i


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef cMutexMerge3_1b.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file cMutexMerge3_1b_utilization_synth.rpt -pb cMutexMerge3_1b_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
